[Settings]

ID = "b6410114-05ec-44d6-a356-ab714023d7e2"

	[build]
		publish = "dist"
		command = "npm run build"
		functions = "lambda"

  [[redirects]]
		from = "/auth"
  	to = "/.netlify/functions/auth"
  	status = 200